apiVersion: v1
kind: Service
metadata:
  name: consul-http
  labels:
    name: consul-http
spec:
  ports:
    - name: http
      port: 8500
      targetPort: http
  selector:
    member: consul-1
  type: NodePort
